server:
  port: 8083

spring:
  application:
    name: shop-cooperation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MySQL_URL}
    username: ${MySQL_USERNAME}
    password: ${MySQL_PASSWORD}


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10

  redis:
    host: localhost
    port: 6379
    password:

  jwt:
    secret: ${JWT_KEY}
    expiration-time: 3600000000000


logging.level:
  org.hibernate.SQL: debug